"""add seen_in_feeds array to indicators

Revision ID: 3a7357601d89
Revises: 766c01985511
Create Date: 2026-07-21 21:03:31.606054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a7357601d89'
down_revision: Union[str, Sequence[str], None] = '766c01985511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('seen_in_feeds', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'seen_in_feeds')
    # ### end Alembic commands ###
