"""fix indicator_count to Integer

Revision ID: 766c01985511
Revises: 1979aaa34571
Create Date: 2026-07-21 02:17:17.556858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766c01985511'
down_revision: Union[str, Sequence[str], None] = '1979aaa34571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feeds', 'indicator_count',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('indicators', 'times_seen',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'1'::smallint"))
    op.drop_constraint(op.f('indicators_value_unique'), 'indicators', type_='unique')
    op.drop_index(op.f('ix_indicators_value'), table_name='indicators')
    op.create_index(op.f('ix_indicators_value'), 'indicators', ['value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_value'), table_name='indicators')
    op.create_index(op.f('ix_indicators_value'), 'indicators', ['value'], unique=False)
    op.create_unique_constraint(op.f('indicators_value_unique'), 'indicators', ['value'], postgresql_nulls_not_distinct=False)
    op.alter_column('indicators', 'times_seen',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'1'::smallint"))
    op.alter_column('feeds', 'indicator_count',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
