import os
from datetime import datetime
from fpdf import FPDF
from sqlalchemy.orm import Session
from .models import Indicator, IndicatorStatus

class ThreatReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(22, 27, 34) # Dark slate
        self.cell(0, 10, "ThreatLens - Executive Threat Posture Report", border=False, ln=True, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(139, 148, 158)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Sentinova Security Systems", align="C")

def generate_executive_pdf(db: Session, file_path: str = "/tmp/executive_report.pdf"):
    """Generates a PDF report of current high-severity threats."""
    pdf = ThreatReportPDF()
    pdf.add_page()
    
    # Title & Meta
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"Report Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC", ln=True)
    pdf.ln(5)
    
    # Query Data
    critical_count = db.query(Indicator).filter(Indicator.severity_score >= 90, Indicator.status == IndicatorStatus.active).count()
    high_count = db.query(Indicator).filter(Indicator.severity_score >= 70, Indicator.severity_score < 90, Indicator.status == IndicatorStatus.active).count()
    
    # Executive Summary Section
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(204, 255, 0) # Neon Green accent
    pdf.cell(0, 10, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    summary_text = (
        f"The Security Operations Center is currently tracking {critical_count} CRITICAL "
        f"and {high_count} HIGH severity indicators of compromise. These represent active, "
        "defended, or escalating threats requiring immediate oversight."
    )
    pdf.multi_cell(0, 8, summary_text)
    pdf.ln(10)
    
    # Top Threats Table Header
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Top Active Threats", ln=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(80, 10, "Indicator Value", border=1)
    pdf.cell(40, 10, "Type", border=1)
    pdf.cell(30, 10, "Severity", border=1)
    pdf.cell(40, 10, "TLP", border=1)
    pdf.ln()
    
    # Top Threats Table Rows
    pdf.set_font("Helvetica", "", 10)
    top_threats = db.query(Indicator).filter(
        Indicator.status == IndicatorStatus.active
    ).order_by(Indicator.severity_score.desc()).limit(10).all()
    
    for threat in top_threats:
        pdf.cell(80, 10, threat.value[:35] + ('...' if len(threat.value) > 35 else ''), border=1)
        pdf.cell(40, 10, threat.type.value.upper(), border=1)
        pdf.cell(30, 10, str(threat.severity_score), border=1, align="C")
        pdf.cell(40, 10, threat.tlp.value.upper(), border=1, align="C")
        pdf.ln()

    pdf.output(file_path)
    return file_path
